#!/bin/bash
# tesla-sync entrypoint — runs inside the container on every start

set -e

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║              Tesla Sync — starting up                ║"
echo "╚══════════════════════════════════════════════════════╝"

# ── 1. Bake current env into a file cron jobs can source ────────────────────
# Docker's env_file injects vars into the container process, but cron jobs
# start in a clean shell and don't inherit them. We export relevant vars
# to /app/.env-cron using Python's shlex.quote for safe quoting.
python3 -c "
import os, shlex
prefixes = ('TESLA_', 'EVC_', 'TESLAMATE_', 'POSTGRES')
lines = ['# Auto-generated by entrypoint.sh — do not edit']
for k, v in sorted(os.environ.items()):
    if any(k.startswith(p) for p in prefixes):
        lines.append(f'export {k}={shlex.quote(v)}')
print('\n'.join(lines))
" > /app/.env-cron
chmod 600 /app/.env-cron
echo "  [env] Cron environment written to /app/.env-cron"

# ── 2. Ensure log files exist (tail -f needs them present at start) ──────────
touch /app/logs/sync_tesla.log /app/logs/sync_evc.log

# ── 3. Check Tesla token ─────────────────────────────────────────────────────
if [ ! -f "$TESLA_TOKEN_FILE" ]; then
    echo ""
    echo "  ┌─────────────────────────────────────────────────────────┐"
    echo "  │  ⚠  Tesla token not found — one-time setup needed:      │"
    echo "  │                                                         │"
    echo "  │  Open a second terminal and run:                        │"
    echo "  │    docker compose exec tesla-sync python scripts/auth.py│"
    echo "  │                                                         │"
    echo "  │  A URL will be printed. Open it in your browser,        │"
    echo "  │  log in to Tesla, then paste the redirect URL back.     │"
    echo "  └─────────────────────────────────────────────────────────┘"
    echo ""
else
    echo "  [auth] Tesla token found at $TESLA_TOKEN_FILE ✓"
fi

# ── 4. Check EVC credentials ─────────────────────────────────────────────────
if [ -z "$EVC_EMAIL" ] || [ -z "$EVC_PASSWORD" ]; then
    echo "  [evc]  EVC_EMAIL / EVC_PASSWORD not set → EVC sync will be skipped"
else
    echo "  [evc]  EVC credentials configured for: $EVC_EMAIL ✓"
fi

# ── 5. Check TeslaMate DB reachability ───────────────────────────────────────
DB_HOST=$(echo "${TESLAMATE_DATABASE_URL:-}" | sed 's|.*@\([^:]*\).*|\1|')
if [ -n "$DB_HOST" ]; then
    echo "  [db]   TeslaMate DB host: $DB_HOST"
fi

echo ""
echo "  Cron schedule (UTC):"
echo "    06:00 — sync_teslamate_costs.py  (Tesla Supercharger costs)"
echo "    06:30 — sync_evc_costs.py        (EVC-Net / Agrisnellaad costs)"
echo ""

# ── 6. Start cron daemon ─────────────────────────────────────────────────────
echo "  [cron] Starting cron daemon..."
cron

echo "  [cron] Running. Tailing logs — use 'docker logs -f tesla-sync' to follow."
echo ""

# Keep the container alive by streaming both log files to stdout.
# This means 'docker logs' shows real-time sync output.
exec tail -F /app/logs/sync_tesla.log /app/logs/sync_evc.log
